# user no user
# host local 8080

#

### 0. rh server test for liveness
GET localhost:8080/hello

# returned a simple json
###

### 1. create testdb
PUT localhost:8080/testdb

# 200 with empty body
###

### 2. list collections on testdb
GET localhost:8080/testdb/

# returned a simple json
###

### 3. create testdb/collection
PUT localhost:8080/testdb/collection

#  201 empty
###

### 4. get collections meta
GET localhost:8080/testdb/collection/_meta

# returned a simple json
###

### 4. delete testdb/collection
#  must supply the If-Match header
DELETE localhost:8080/testdb/collection
If-Match: 5dcc4456dec30b59e21572dc
#  204 no content empty
###

### 5. create testdb/collection
PUT localhost:8080/testdb/test-coll

#  201 empty
###
