# user no user
# host local 8080

#

### 0.  sanity check local
#
#   check
GET localhost:8081/api/item
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqdXNlckBkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6InZkanVzZXIiLCJ0YXBpcy9hY2NvdW50X3R5cGUiOiJ1c2VyIiwiZXhwIjoxNjA0NjgwMjE0fQ.wtEF7XdeaJqnCVgb0ay4zmImdVlSY3IOfvfafMYe6Gle5fZWu-hoHu_xRoxU47IWpgtf27G7LKP4O84q0_jXuo2GelrjVSHnfnUqJz6nLcczZ5hbTgZna-E0YQtWiNfYxUbFnTzGpYkglgBcj5OUVJbY_aVNpGb28MnGnCo8tr9pclx2HKVjFkSArZu2cKYL7XriLsa_04T0wQ-YhWeRFm3rF1cwI6Bv3syorJeA-wprPQajByRLq7BgUSmRXDRZ-7Jbo0dyx55cw5dEh4UnBisMDk-zz2Cu6DImr7HS9ud6L1cFfeYNoFI2Og5U7xboQ4u87IwR8Ilj4SDvqKodlw
# Content-Type: application/json

###

