# user no user
# host local 8080

#

### 0.  sanity check local
#
#   check vdjadmin token
GET localhost:18080/v3/meta/testdb/_meta
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

#   check vdjadmin token
#  create a new db
PUT localhost:18080/v3/meta/testdb
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

#  list db names
GET http://c002.rodeo.tacc.utexas.edu:32671/echo
# X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

#  list db names
GET http://c002.rodeo.tacc.utexas.edu:32671/meta/v3/testdb
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3...ZUvVVkfeQpUaiDR6GViX2aNa9aekC65VkNXLyL2ixIevCL-MMmC2X2Pbczhya5b4clMRjkSMgJ_vsrv5trKD_fNUeZ9gExHemvxf63wpK6zI3MDPT6l5A
# Content-Type: application/json

###
