
#   check vdjadmin token
#  create a new db
PUT c002.rodeo.tacc.utexas.edu:32671/v3/meta/streams
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

#   check vdjadmin token
#  create a new collection
PUT c002.rodeo.tacc.utexas.edu:32671/v3/meta/streams/proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

##################################################################

#   check vdjadmin token  list dbs
GET c002.rodeo.tacc.utexas.edu:32671/v3/meta
# GET dev.develop.tapis.io/v3/meta
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
Content-Type: application/json

###

#   check vdjadmin token list collections on StreamsTACCDB
GET c002.rodeo.tacc.utexas.edu:32671/v3/meta/StreamsTACCDB
# GET dev.develop.tapis.io/v3/meta
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
Content-Type: application/json

###

#   check vdjadmin token
GET c002.rodeo.tacc.utexas.edu:32671/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
Content-Type: application/json

###


#   check vdjadmin token
# PUT c002.rodeo.tacc.utexas.edu:30401/testdb
# X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

################################################### streams testing ###################################################
#   tapis dev env
#   check streams token backdoor wo security front end
GET c002.rodeo.tacc.utexas.edu:30401/StreamsTACCDB
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
Content-Type: application/json

###
# success

#   local env with security and tapis dev env for RH core -> mongo
#   using vdjadmin token
GET 127.0.0.1:18080/v3/meta/streams
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
Content-Type: application/json

###


##################################### testuser1 #################################################
#   local env with security and tapis dev env for RH core -> mongo
#   using testuser1 token can we list all the collections under StreamsTACCDB
#    no we cannot so we can't DELETE the collection either.

# testuser1  CRUD
# can't get a collection list under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIxQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIxIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTcyMjE1M30.jmWcivJzz9RPgnOzRP8dGP-LhpzaR32krRm8ADV5UaSWtXEyQnIqtlUjXNz5HKQ6I4ixH3p_p7YnVY0ACmKdkA0sQ-ByIkRv3fYIqAhgutJBHoGoUOqUXbtwonai4NOS4CyXcpCgGbARxx1eSUvMqTEgH-K-AzlN_bMFGxlLpVPq1Fdkl2ALjP2R_VeDlh0jGvjrdGAPVfJIVVhbcn8wRomDAm_V2ig0Sx7V-U3D9fBRr29kiN5a88f8GYK53gwpdpdS_Q9m5TtOxsN6KuBq2E_-_Fp-Ad0k4ySE6A7xiZ1oyCPAgzGGQPsIUDTyFhRzyMOM8dVXsI1Go_s3XnKVYQ
Content-Type: application/json

###

# testuser1
#  list documents under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIxQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIxIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTcyMjE1M30.jmWcivJzz9RPgnOzRP8dGP-LhpzaR32krRm8ADV5UaSWtXEyQnIqtlUjXNz5HKQ6I4ixH3p_p7YnVY0ACmKdkA0sQ-ByIkRv3fYIqAhgutJBHoGoUOqUXbtwonai4NOS4CyXcpCgGbARxx1eSUvMqTEgH-K-AzlN_bMFGxlLpVPq1Fdkl2ALjP2R_VeDlh0jGvjrdGAPVfJIVVhbcn8wRomDAm_V2ig0Sx7V-U3D9fBRr29kiN5a88f8GYK53gwpdpdS_Q9m5TtOxsN6KuBq2E_-_Fp-Ad0k4ySE6A7xiZ1oyCPAgzGGQPsIUDTyFhRzyMOM8dVXsI1Go_s3XnKVYQ
Content-Type: application/json

###

# testuser1
#  add document under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
POST 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIxQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIxIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTcyMjE1M30.jmWcivJzz9RPgnOzRP8dGP-LhpzaR32krRm8ADV5UaSWtXEyQnIqtlUjXNz5HKQ6I4ixH3p_p7YnVY0ACmKdkA0sQ-ByIkRv3fYIqAhgutJBHoGoUOqUXbtwonai4NOS4CyXcpCgGbARxx1eSUvMqTEgH-K-AzlN_bMFGxlLpVPq1Fdkl2ALjP2R_VeDlh0jGvjrdGAPVfJIVVhbcn8wRomDAm_V2ig0Sx7V-U3D9fBRr29kiN5a88f8GYK53gwpdpdS_Q9m5TtOxsN6KuBq2E_-_Fp-Ad0k4ySE6A7xiZ1oyCPAgzGGQPsIUDTyFhRzyMOM8dVXsI1Go_s3XnKVYQ
Content-Type: application/json

{ "name" : "testdocument POST" }

###

# testuser1
#  PUT document under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
PUT 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1/5e29edf5892d452cbb00d83a
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIxQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIxIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTcyMjE1M30.jmWcivJzz9RPgnOzRP8dGP-LhpzaR32krRm8ADV5UaSWtXEyQnIqtlUjXNz5HKQ6I4ixH3p_p7YnVY0ACmKdkA0sQ-ByIkRv3fYIqAhgutJBHoGoUOqUXbtwonai4NOS4CyXcpCgGbARxx1eSUvMqTEgH-K-AzlN_bMFGxlLpVPq1Fdkl2ALjP2R_VeDlh0jGvjrdGAPVfJIVVhbcn8wRomDAm_V2ig0Sx7V-U3D9fBRr29kiN5a88f8GYK53gwpdpdS_Q9m5TtOxsN6KuBq2E_-_Fp-Ad0k4ySE6A7xiZ1oyCPAgzGGQPsIUDTyFhRzyMOM8dVXsI1Go_s3XnKVYQ
Content-Type: application/json

{ "name" : "testdocument PUT" }

###

# testuser1
#  delete document under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
DELETE 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1/5e29edf5a93eebf39fba902a
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIxQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIxIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTcyMjE1M30.jmWcivJzz9RPgnOzRP8dGP-LhpzaR32krRm8ADV5UaSWtXEyQnIqtlUjXNz5HKQ6I4ixH3p_p7YnVY0ACmKdkA0sQ-ByIkRv3fYIqAhgutJBHoGoUOqUXbtwonai4NOS4CyXcpCgGbARxx1eSUvMqTEgH-K-AzlN_bMFGxlLpVPq1Fdkl2ALjP2R_VeDlh0jGvjrdGAPVfJIVVhbcn8wRomDAm_V2ig0Sx7V-U3D9fBRr29kiN5a88f8GYK53gwpdpdS_Q9m5TtOxsN6KuBq2E_-_Fp-Ad0k4ySE6A7xiZ1oyCPAgzGGQPsIUDTyFhRzyMOM8dVXsI1Go_s3XnKVYQ
Content-Type: application/json

###


##################################### testuser2 #################################################
# testuser2   CRU
# can't get a collection list under StreamsTACCDB /v3/meta/StreamsTACCDB/
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIyQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIyIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzg0NX0.GNv-4VBbaRZfGp3ry60BLLo4m7pEhqEZJzA2u2bpGaL5Rhv0cbD6bnmFj38RW6PSFM-tDFeL_DKZVCAiZz46B_nXf5nEHTkrBmV30odgqA7cRYw9jJ6ZxfNpx1myq2KqwL4mBqqUNKS3ghKyOaS5-txRelZh4xzBhyHQ4OGms0-QKOwJBBKn8o5Us0ME3UGez5n3Gq8YMdIHPWCPfo6aQsVA2W7zGXUchvNRO0sR4LP-osUMIfCXzIokdKJ7YUV5Z6g--UN1yFZolEFysXdrMhKFGqokUTwz7IDIIRXXVu26WdpxMWeUTQWP9JGelrtxJLSTbnFAfDjjSUaJVGO8AQ
Content-Type: application/json

###

# testuser2   CRU
#  list documents under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIyQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIyIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzg0NX0.GNv-4VBbaRZfGp3ry60BLLo4m7pEhqEZJzA2u2bpGaL5Rhv0cbD6bnmFj38RW6PSFM-tDFeL_DKZVCAiZz46B_nXf5nEHTkrBmV30odgqA7cRYw9jJ6ZxfNpx1myq2KqwL4mBqqUNKS3ghKyOaS5-txRelZh4xzBhyHQ4OGms0-QKOwJBBKn8o5Us0ME3UGez5n3Gq8YMdIHPWCPfo6aQsVA2W7zGXUchvNRO0sR4LP-osUMIfCXzIokdKJ7YUV5Z6g--UN1yFZolEFysXdrMhKFGqokUTwz7IDIIRXXVu26WdpxMWeUTQWP9JGelrtxJLSTbnFAfDjjSUaJVGO8AQ
Content-Type: application/json

###

# testuser2    CRU
#  add document under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
POST 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIyQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIyIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzg0NX0.GNv-4VBbaRZfGp3ry60BLLo4m7pEhqEZJzA2u2bpGaL5Rhv0cbD6bnmFj38RW6PSFM-tDFeL_DKZVCAiZz46B_nXf5nEHTkrBmV30odgqA7cRYw9jJ6ZxfNpx1myq2KqwL4mBqqUNKS3ghKyOaS5-txRelZh4xzBhyHQ4OGms0-QKOwJBBKn8o5Us0ME3UGez5n3Gq8YMdIHPWCPfo6aQsVA2W7zGXUchvNRO0sR4LP-osUMIfCXzIokdKJ7YUV5Z6g--UN1yFZolEFysXdrMhKFGqokUTwz7IDIIRXXVu26WdpxMWeUTQWP9JGelrtxJLSTbnFAfDjjSUaJVGO8AQ
Content-Type: application/json

{ "name" : "testdocument POST testuser2" }

###

# testuser2 CRU
#  PUT document under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###   gives forbidden
PUT 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1/5e29fa28a93eebf39fba927b
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIyQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIyIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzg0NX0.GNv-4VBbaRZfGp3ry60BLLo4m7pEhqEZJzA2u2bpGaL5Rhv0cbD6bnmFj38RW6PSFM-tDFeL_DKZVCAiZz46B_nXf5nEHTkrBmV30odgqA7cRYw9jJ6ZxfNpx1myq2KqwL4mBqqUNKS3ghKyOaS5-txRelZh4xzBhyHQ4OGms0-QKOwJBBKn8o5Us0ME3UGez5n3Gq8YMdIHPWCPfo6aQsVA2W7zGXUchvNRO0sR4LP-osUMIfCXzIokdKJ7YUV5Z6g--UN1yFZolEFysXdrMhKFGqokUTwz7IDIIRXXVu26WdpxMWeUTQWP9JGelrtxJLSTbnFAfDjjSUaJVGO8AQ
Content-Type: application/json

{ "name" : "testdocument PUT testuser2" }

###

# testuser2
#  delete document under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
DELETE 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1/5e29fa28a93eebf39fba927b
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIyQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIyIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzg0NX0.GNv-4VBbaRZfGp3ry60BLLo4m7pEhqEZJzA2u2bpGaL5Rhv0cbD6bnmFj38RW6PSFM-tDFeL_DKZVCAiZz46B_nXf5nEHTkrBmV30odgqA7cRYw9jJ6ZxfNpx1myq2KqwL4mBqqUNKS3ghKyOaS5-txRelZh4xzBhyHQ4OGms0-QKOwJBBKn8o5Us0ME3UGez5n3Gq8YMdIHPWCPfo6aQsVA2W7zGXUchvNRO0sR4LP-osUMIfCXzIokdKJ7YUV5Z6g--UN1yFZolEFysXdrMhKFGqokUTwz7IDIIRXXVu26WdpxMWeUTQWP9JGelrtxJLSTbnFAfDjjSUaJVGO8AQ
Content-Type: application/json

###

# testuser2   CRU
#  list documents under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1/
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIyQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIyIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzg0NX0.GNv-4VBbaRZfGp3ry60BLLo4m7pEhqEZJzA2u2bpGaL5Rhv0cbD6bnmFj38RW6PSFM-tDFeL_DKZVCAiZz46B_nXf5nEHTkrBmV30odgqA7cRYw9jJ6ZxfNpx1myq2KqwL4mBqqUNKS3ghKyOaS5-txRelZh4xzBhyHQ4OGms0-QKOwJBBKn8o5Us0ME3UGez5n3Gq8YMdIHPWCPfo6aQsVA2W7zGXUchvNRO0sR4LP-osUMIfCXzIokdKJ7YUV5Z6g--UN1yFZolEFysXdrMhKFGqokUTwz7IDIIRXXVu26WdpxMWeUTQWP9JGelrtxJLSTbnFAfDjjSUaJVGO8AQ
Content-Type: application/json

###



##################################### testuser3 #################################################
# testuser3   CRU
# can't get a collection list under StreamsTACCDB /v3/meta/StreamsTACCDB/
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIzQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIzIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzk0N30.rC5wEOH33h_RXfEzkEJPnOqjPS2uddZ23NUr6xxu2nh9v7zYyVOfh05pR2YQt01quVja8KGPMZB0vQWzyQWZMXOtq94UhBV7HjhWgcboxeHOoOEO4TTP1HPQrKGhw87RoUPDUSsav2OShLfdopp91jbSFREsGEIKse4-NOjv6iOoPtjkF1FEB-JWLtFEL9YCNXe7YHCxF3tr3BtD0P4ho7b7W-RAEmqrjUyYXmxjJIbs9b6N-Or5Y52y2F7mqzkpTtGzzaZkadRxU2sXAwdRyhI3X2cmdxaOWR3BJVJK8NfaJvsrzRjsV8gIULEF7HpnbR6DQH2KGxKkN4P3t5Tz6A
Content-Type: application/json

###

# testuser3   CRU
#  list documents under StreamsTACCDB /v3/meta/StreamsTACCDB/Proj1
###
GET 127.0.0.1:18080/v3/meta/StreamsTACCDB/Proj1
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoidGVzdHVzZXIzQGRldiIsInRhcGlzL3RlbmFudF9pZCI6ImRldiIsInRhcGlzL3Rva2VuX3R5cGUiOiJhY2Nlc3MiLCJ0YXBpcy9kZWxlZ2F0aW9uIjpmYWxzZSwidGFwaXMvZGVsZWdhdGlvbl9zdWIiOm51bGwsInRhcGlzL3VzZXJuYW1lIjoidGVzdHVzZXIzIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTU4OTgwMzk0N30.rC5wEOH33h_RXfEzkEJPnOqjPS2uddZ23NUr6xxu2nh9v7zYyVOfh05pR2YQt01quVja8KGPMZB0vQWzyQWZMXOtq94UhBV7HjhWgcboxeHOoOEO4TTP1HPQrKGhw87RoUPDUSsav2OShLfdopp91jbSFREsGEIKse4-NOjv6iOoPtjkF1FEB-JWLtFEL9YCNXe7YHCxF3tr3BtD0P4ho7b7W-RAEmqrjUyYXmxjJIbs9b6N-Or5Y52y2F7mqzkpTtGzzaZkadRxU2sXAwdRyhI3X2cmdxaOWR3BJVJK8NfaJvsrzRjsV8gIULEF7HpnbR6DQH2KGxKkN4P3t5Tz6A
Content-Type: application/json

###
