#########################     RH security calls     #########################
### 0.  sanity check RH security front end.
#
#   check vdjadmin token against RH security returns a list of DBs at root "/v3/meta/"
GET dev.develop.tapis.io/v3/meta
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###

#  1. create a new db  vdjadmin token
PUT dev.develop.tapis.io/v3/meta/v1airr
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw

###

#  2. list collections
GET https://dev.develop.tapis.io/v3/meta/testdb
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw

###

#  3. create a new collection  vdjadmin token
PUT https://dev.develop.tapis.io/v3/meta/testdb/sltcollection
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
# Content-Type: application/json

###
#  4. list documents
GET https://dev.develop.tapis.io/v3/meta/testdb/sltcollection
X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoidmRqYWRtaW5AZGV2IiwidGFwaXMvdGVuYW50X2lkIjoiZGV2IiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJ2ZGphZG1pbiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MDQ2ODAzMzR9.FvlNWjy1rOZFGtGJbNqahD4zbmnpBc9PywvFLvPX54vfZB3DIu0sIkES0yTjjAg0qxdQdYhHAyKrV1Kbl7C89a4XEIyljqembWnGCuCLkNy6zmn1Bqj3osJn7Zdm7wAmuwTxg2jPH9Yim-C09-gmijNNKqs_sn_IhPKcs4718PBRWM6V8jCJY7U7kIlklc8Ngg1S6TCQ8K1kidCa2CcOZNzKWw3lfAYY8up-9rNCb88Luujv-ZPN2bC6TAPwKMwiiR9Z-rfAzTv8ftevDoQlFp6WWovsK1GRok8TWbCL5t9wzhZ04mh1XkRJm9m_LVubfdZAG19X8wOV_pNj8n9Kmw
Content-Type: application/json

###




###   one off to add vdjadmin role to pysdk user
# POST https://dev.develop.tapis.io/v3/security/user/grantRole
# X-Tapis-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2Rldi5hcGkudGFwaXMuaW8vdG9rZW5zL3YzIiwic3ViIjoibWV0YUBkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6Im1ldGEiLCJ0YXBpcy9hY2NvdW50X3R5cGUiOiJzZXJ2aWNlIiwiZXhwIjoxNjA0NjgwNjY3fQ.XXd7ZZgZJfP6mcwzYF5PdcHBkTB2dXTJTOljtT9xTIkkz-QV5v-_eHFzZWshJH4Hns4b6nGF-1eBoy_VugmHoMFWPFcC9RijBlM1brReSEr47PXgERPWazPgJecGzwfxSELE4xECIlVKd1GlHiQc7t4B-xhZ1FzbcT1eJmzI5D5Wp54A3Eytq7HU2o6RWN_8ARxgcWece0bKCPWpYF3tVhuH5y_-6lomp6nrcx8JgqdwpmGLtqFqf5zHmVMDt61GlneMou3C4OwVrCvhF0ZNXE4eQDmWgi0-5k9HJDGbrEz5BLT_RuTe6GZ-42DsICrjQHjYQ_m_ALgreDmT-ARgeQ
# Content-Type: application/json

# { "user": "pysdk", "roleName":"vdjadmin" }

###
